// 角色模板数据（固定不变）
// 添加新角色只需在此文件末尾追加 { name: '角色名', totalUses: 数字 } 即可
// 头像图片会自动从 character/ 文件夹中按角色名匹配（支持 png/jpg/jpeg/webp/gif）
const characterTemplates = [
  { name: '漂泊者', totalUses: 1 },
  { name: '秧秧', totalUses: 1 },
  { name: '炽霞', totalUses: 1 },
  { name: '白芷', totalUses: 2 },
  { name: '散华', totalUses: 1 },
  { name: '桃祈', totalUses: 1 },
  { name: '丹瑾', totalUses: 1 },
  { name: '秋水', totalUses: 1 },
  { name: '莫特斐', totalUses: 1 },
  { name: '渊武', totalUses: 1 },
  { name: '釉瑚', totalUses: 1 },
  { name: '灯灯', totalUses: 1 },
  { name: '卜灵', totalUses: 2 },


  { name: '维里奈', totalUses: 2 },
  { name: '安可', totalUses: 1 },
  { name: '凌阳', totalUses: 1 },
  { name: '鉴心', totalUses: 1 }, 
  { name: '卡卡罗', totalUses: 1 },

  { name: '忌炎', totalUses: 1 },
  { name: '今汐', totalUses: 1 },
  { name: '长离', totalUses: 1 },
  { name: '相里要', totalUses: 1 },
  { name: '吟霖', totalUses: 1 },
  { name: '守岸人', totalUses: 2 },
  { name: '椿', totalUses: 1 },

  { name: '珂莱塔', totalUses: 1 },
  { name: '折枝', totalUses: 1 },
  { name: '洛可可', totalUses: 1 },
  { name: '赞妮', totalUses: 1 },
  { name: '菲比', totalUses: 1 },
  { name: '弗洛洛', totalUses: 1 },
  { name: '坎特蕾拉', totalUses: 1 },
  { name: '卡提希娅', totalUses: 1 },
  { name: '夏空', totalUses: 1 },
  { name: '千咲', totalUses: 1 },
  { name: '布兰特', totalUses: 1 },
  { name: '露帕', totalUses: 1 },
  { name: '嘉贝莉娜', totalUses: 1 },
  { name: '奥古斯塔', totalUses: 1 },
  { name: '尤诺', totalUses: 1 },
  
  { name: '爱弥斯', totalUses: 1 },
  { name: '琳奈', totalUses: 1 },
  { name: '莫宁', totalUses: 2 },
  { name: '陆·赫斯', totalUses: 1 },
  { name: '西格莉卡', totalUses: 1 },
  { name: '仇远', totalUses: 1 },
  { name: '达妮娅', totalUses: 1 },
  { name: '绯雪', totalUses: 1 },
  { name: '洛瑟拉', totalUses: 1 },
  { name: '露西', totalUses: 1 },
  { name: '丽贝卡', totalUses: 1 },
  { name: '秧秧·玄翎', totalUses: 1 },
  { name: '穗穗', totalUses: 2 },
  { name: '清宵', totalUses: 1 },
  { name: '景燃', totalUses: 1 },
  { name: '心', totalUses: 1 },
  { name: '锁暝', totalUses: 1 },

  //{ name: 'None', totalUses: 1 },
  // ...后续手动追加
];
